# copied from pascal and more

# arguments for dataset
dataset: tless
nclass: 31
crop_size: 512
data_root: /data/tless
valset: test_primesense

# arguments for training
epochs: 31
epochsToRun: 1
batch_size: 4 # per GPU x 2 GPUs
lr: 0.005
lr_multi: 10.0
criterion:
  name: CELoss
  kwargs:
    ignore_index: 255
conf_thresh: 0.95

# arguments for model
model: deeplabv3plus
backbone: resnet101
replace_stride_with_dilation: [False, False, True]
dilations: [6, 12, 18]
